name: Build Test Node Docker Image
on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*.*.*'

env:
  IMAGE_NAME: aelf-test-node
  DOCKER_FILE: AElf/build/Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
        with:
          submodules: true

      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Run build-aelf.sh script
        run: bash build-aelf.sh dotnet-build --version 1.0.0

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Copy config files
        run: cp -r config/* AElf/build/

      -
        name: Copy Dockerfile
        run: cp -r Dockerfile AElf/build/

      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ env.DOCKER_FILE }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}